# Site settings
title: 垃圾场
SEOTitle: 垃圾场中的战斗机 | LESE Blog
header-img: img/home-bg.jpg
email: jasoncpp@outlook.com
description: "计算机视觉 强化学习 生成对抗学习 深度学习"
keyword: "@Jason,@Jason的博客, 博客, 个人网站"
url: "https://jason-cpp.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
weibo_username:     no
zhihu_username:     li-zhi-qi-98-19
github_username:    Jason-cpp
linkedin_username:  no
twitter_username:   no
facebook_username:  no



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
textColor: #FF0000
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN  

# Back to top 回到顶部by ray-eldath
b2t: true

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]
plugins: [jekyll-sitemap]
gems: [jekyll-sitemap]
paginate_path: "page:num"   #分页页面路径格式



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Comment
#comment:
    #disqus: yizibi

# Netease settings
netease_comment: false

gitalk:
   enable: true
   owner: Jason-cpp
   repo: jason-cpp.github.io
   clientID: 5af90a3c38b3b7dc21bf
   clientSecret: 71fb600d3c36a0fa39590215f17cb2d0f038ffa8
   admin: Jason-cpp


# Analytics settings
Baidu Analytics 
ba_track_id: 2e014a9060d8e8e4dce81c5a46e2c3ef

# Google Analytics
#ga_track_id: 'GTM-P93BGWV'            # Format: UA-xxxxxx-xx
#ga_domain: auto



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: “大圣，此去欲何？”<br>“踏南天，碎凌霄”<br>“如若一去不回……？”<br>“便一去不回！💪"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
   # {
#	title: "Junhua's Blog",
#	href: "https://blog.searchinfogo.com"
 #   },{

]
